services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    image: ${APP_IMAGE:-order-web:latest}
    container_name: order-web
    restart: unless-stopped

    env_file:
      - .env

    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /app/secrets/gcs-service-account.json

    volumes:
      - ./secrets/gcs-service-account.json:/app/secrets/gcs-service-account.json:ro

    ports:
      - "3000:3000"

    networks:
      - order-network

networks:
  order-network:
    driver: bridge
